%YAML 1.1
---

project:
    defination: "Conway's Game of Life - Adaptation of Simulation Theory"
    topic: "Simulation - AI - AGI - Knowledge Retrieval"
    focus: "Practice & Principles of Simulation Theory"
    affiliated: "Memoriae Technology"
    creater: "Baris Dincer / Co-Founder of Memoriae"
    link: "https://www.linkedin.com/in/brs-dincer/"